FROM node:18-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
COPY /environments /usr/src/app/environments
RUN npm ci --omit=dev
COPY . .
RUN npm run build
FROM node:18-alpine AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN  npm ci --only=production --omit=dev
COPY --from=development /usr/src/app/dist/apps/enrollment-micro ./dist/apps/enrollment-micro
COPY --from=development /usr/src/app/environments ./environments
USER node
EXPOSE 3000
CMD ["npm", "run", "start:prod"]