FROM node:18-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
COPY /environments /usr/src/app/environments
RUN npm ci --omit=dev
COPY . .
RUN npm run build
FROM node:18-alpine AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production --omit=dev
COPY --from=development /usr/src/app/dist/apps/transactions-micro ./dist/apps/transactions-micro
COPY --from=development /usr/src/app/environments ./environments
USER node
EXPOSE 3002
CMD ["npm", "run", "start-transactions:prod"]