FROM node:18-alpine AS development
WORKDIR /usr/src/app
COPY package*.json ./
COPY /environments /usr/src/app/environments
RUN npm install
COPY . .
RUN npm run build
FROM node:18-alpine AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production --omit=dev
COPY --from=development /usr/src/app/dist ./dist
COPY --from=development /usr/src/app/environments ./environments
CMD ["npm", "run", "start-transactions:prod"]