version: '3.9'

services:
  # mongodb:
  #   image: mongo
  #   restart: always
  #   container_name: MongoDB
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./data/mongo:/data/db
  auth-micro:
    image: auth-micro:version1
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
      - kafka
    ports:
      - 3004:3004
  enrollment-micro:
    image: enrollment-micro:version1
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
      - kafka
    ports:
      - 3000:3000
  transactions-micro:
    image: transactions-micro:version1
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
      - kafka
    ports:
      - 3002:3002
  postgres:
    image: postgres
    restart: always
    container_name: PostgreSQL
    networks:
      - backend
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: ZooKeeper
    networks:
      - backend
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    hostname: Kafka
    container_name: Kafka
    networks:
      - backend
    links:
      - zookeeper
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    networks:
      - backend
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

networks:
  backend:
    driver: bridge
